server:
  port: 45672
logging:
  level:
    org.springframework.amqp: debug
spring:
  application:
    name: rabbit-consumer
# 自定义Rabbit-Consumer监听的队列
queue:
  direct:
    first: firstDirect
    second: secondDirect